# Bocher Diedrich Sandmeier
#
# compile command: make
# create file with output for 1 <= k <= 20 program: make 20

CC=gcc # compiler to be used

switchMonths.x: switchMonths.c
	$(CC) -o switchMonths.x switchMonths.c -Wall -Werror
	
test:
	./switchMonths.x 2017 